### ISSUE TITLE
ld: library not found for -lWebEngageAppEx

### ISSUE THREAD

**Issue by karthikmandava7** [WebEngage/react-native-webengage#23]
Link NotificationViewController (arm64)

Ld /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator/NotificationViewController.appex/NotificationViewController normal (in target 'NotificationViewController' from project 'ReactNativeMobileApp')
    cd /Users/macbook_m1/Documents/New_RN/react-native-mobile-app/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios10.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk -L/Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator -L/Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator/WebEngageAppEx -F/Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator -filelist /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Intermediates.noindex/ReactNativeMobileApp.build/Debug-iphonesimulator/NotificationViewController.build/Objects-normal/arm64/NotificationViewController.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Intermediates.noindex/ReactNativeMobileApp.build/Debug-iphonesimulator/NotificationViewController.build/Objects-normal/arm64/NotificationViewController_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fapplication-extension -ObjC -lWebEngageAppEx -framework Foundation -weak_framework UserNotifications -weak_framework UserNotificationsUI -e _NSExtensionMain -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Intermediates.noindex/ReactNativeMobileApp.build/Debug-iphonesimulator/NotificationViewController.build/NotificationViewController.appex-Simulated.xcent -framework UserNotificationsUI -framework UserNotifications -lPods-NotificationViewController -Xlinker -dependency_info -Xlinker /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Intermediates.noindex/ReactNativeMobileApp.build/Debug-iphonesimulator/NotificationViewController.build/Objects-normal/arm64/NotificationViewController_dependency_info.dat -o /Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator/NotificationViewController.appex/NotificationViewController

ld: warning: directory not found for option '-L/Users/macbook_m1/Library/Developer/Xcode/DerivedData/ReactNativeMobileApp-gbqoyqlixmhqizflvioibvialbrf/Build/Products/Debug-iphonesimulator/WebEngageAppEx'
ld: library not found for -lWebEngageAppEx
clang: error: linker command failed with exit code 1 (use -v to see invocation)

using M1 MacBook Air, but it is working on Intel MacBook Air

**Comment by vatsmanu** [comment]
facing the same issue after react native upgrade from 0.63.3 to 0.65.1 on m1 as well as intel MacBook

**Comment by JapeshFlyFin** [comment]
Facing same issue on  M1 MacBook Air MCOS 13 Xcode 14

**Comment by kekarot1** [comment]
Facing the same issue on M1 machine after updating to Xcode 14.3. Please let me know if there's any solution.

**Comment by nikit-psl** [comment]
Any solutions for this issue yet? Facing a similar issue with WebEngageBannerPush Module
![image](https://github.com/WebEngage/react-native-webengage/assets/100762274/61fee582-ec02-4ca5-913d-82051662cf09)

**Comment by akshay-engage** [comment]
The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "webenagage" framework. Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.

To address this concern effectively, we strongly recommend following these steps:

1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes.

2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict.

3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate.

We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
