### ISSUE TITLE
build failing in release mode 

### ISSUE THREAD

**Issue by christopher-18** [WebEngage/react-native-webengage#27]
Hi, 
Trying to run the code in the release mode in simulator, but getting this error ->

<img width="960" alt="Screenshot 2021-10-28 at 17 05 24" src="https://user-images.githubusercontent.com/23613887/139248086-6bc5d1c7-57de-472b-ae7a-e5f7efcba6e3.png">

Using   "react-native-webengage": "^1.1.1", in package.json
Following are the pod file configuations

  pod 'react-native-webengage', :path => '../node_modules/react-native-webengage'
  pod 'WebEngage', '~> 5.0.2'
  
  It was working fine few days back, but now it's not.
  Please help.

**Comment by abhikb101** [comment]
Getting same issue, any updates on tthis?

**Comment by anujmpec** [comment]
any update?

**Comment by Akshay-Niveus** [comment]
Getting same issue, any update?

**Comment by imanshul** [comment]
Getting same issue, no update from dev team.
Undefined symbol: _OBJC_CLASS_$_WebEngage
React-Native versoin 0.67.2
Web engage version:  "^1.2.10",
POD framework version : 1.3.0

**Comment by anujmpec** [comment]
please fix this issue.

**Comment by akshay-engage** [comment]
The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "webenagage" framework. Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.

To address this concern effectively, we strongly recommend following these steps:

1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes.

2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict.

3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate.

We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
