### ISSUE TITLE
Delete Account Functionality

### ISSUE THREAD

**Issue by Himatheja** [WebEngage/react-native-webengage#40]
Once the user deletes account, the info of the user not to be stored in any platform as per iOS guidelines (Security Concern)

**Comment by akshay-engage** [comment]
In order to delete users, you can utilize GDPR requests. It's necessary to integrate this feature at your end and submit a GDPR request for each user individually.

After submitting the GDPR request, it will take approximately 7 days to delete those users. During this period, you can mark those users as 'Unreachable' for all campaigns via CSV until the deletion is complete.

For more detailed information and instructions on GDPR requests, please refer to our documentation: [WebEngage GDPR Requests Documentation](https://docs.webengage.com/docs/rest-api-gdpr-requests)."

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
