### ISSUE TITLE
Upgrading to react native 0.70

### ISSUE THREAD

**Issue by MShokry** [WebEngage/react-native-webengage#42]
I can't run the application once upgraded to 0.70

Error:
error build: Undefined symbol: _OBJC_CLASS_$_WebEngage

`
// /AppDelegate.mm
#import <WebEngage/WebEngage.h>
#import <WebEngage/WEGUser.h>
#import <WebEngage/WEGAnalytics.h>
// ServiceExtension-Bridging-Header.h (Optional)

....
  [[WebEngage sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
`

`
//AppDelegate.h
#import <WEGWebEngageBridge.h>
#import <UserNotifications/UNUserNotificationCenter.h>

@property (nonatomic, strong) WEGWebEngageBridge *bridge;

`

**Comment by Akshay-Niveus** [comment]
Getting this same, just after updating xcode version not after upgrading react-native

**Comment by imanshul** [comment]
I'm also facing the same issue : Undefined symbol: _OBJC_CLASS_$_WebEngage
I'm using 0.67.2 react native version

**Comment by MShokry** [comment]
I fixed it by
/node_modules/react-native-webengage/react-native-webengage.podspec
Replace 
s.dependency 'WebEngage'
With
s.dependency 'WebEngage/XCFramework'



this is my patch package

`diff --git a/node_modules/react-native-webengage/react-native-webengage.podspec b/node_modules/react-native-webengage/react-native-webengage.podspec
index 7df2a55..32b8962 100644
--- a/node_modules/react-native-webengage/react-native-webengage.podspec
+++ b/node_modules/react-native-webengage/react-native-webengage.podspec
@@ -18,6 +18,6 @@ Pod::Spec.new do |s|
   s.preserve_paths = 'LICENSE.md', 'README.md', 'package.json', 'index.js'
   s.source_files   = 'ios/*.{h,m}'
 
-  s.dependency 'WebEngage'
+  s.dependency 'WebEngage/XCFramework'
   s.dependency 'React-Core'
 end
`

**Comment by imanshul** [comment]
@MShokry For me editing the dependency causes below mentioned error.

Multiple commands produce '/Users/<username>/Library/Developer/Xcode/DerivedData/CASHe-arjxvdapvhtnrkdlezeeoqyybkts/Build/Products/Debug-iphonesimulator/CASHe.app/Frameworks/WebEngage.framework'

**Comment by MShokry** [comment]
@imanshul try to clean the app and re-install pods

npx react-native-clean-project

pod install

**Comment by antilakash** [comment]
Support for new architecture

**Comment by imanshul** [comment]
Even after cleaning build folder, removing podfile.lock and pods directory along with derived data, still i'm facing same issue.

**Comment by akshay-engage** [comment]
The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "webenagage" framework. Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.

To address this concern effectively, we strongly recommend following these steps:

1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes.

2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict.

3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate.

We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
