### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_WebEngage

### ISSUE THREAD

**Issue by imanshul** [WebEngage/react-native-webengage#43]
I'm getting above error in my NotificationServices and NotificationViewController while running the app.

React Native version:

"react-native": "0.67.2",
"react-native-webengage": "^1.2.10",

Pod:
react-native-webengage 1.3.0

**Comment by MShokry** [comment]
@imanshul  try this https://github.com/WebEngage/react-native-webengage/issues/42#issuecomment-1321916407

**Comment by akshay-engage** [comment]
The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "webenagage" framework. Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.

To address this concern effectively, we strongly recommend following these steps:

1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes.

2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict.

3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate.

We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
