### ISSUE TITLE
React Native 0.60.X support

### ISSUE THREAD

**Issue by guggume** [WebEngage/react-native-webengage#6]
Is there a plan for migrating to 0.60.X ?

https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide

Pods were not working from a longtime for RNWebengage
[!] No podspec found for `RNWebengage` in `../node_modules/react-native-webengage`

The only way was manual integration by drag and drop to libraries
In React native  0.60.0 and above they've moved all react deps to pods
RNWEbengage fails when trying to import RCTBridge.

**Comment by pushpendra-choudhary** [comment]
I also tried with manual linking but now stuck with below error. Do you have any workaround for that?

```
fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
```

**Comment by ashwindmk** [comment]
This issue has been fixed in the react-native-webengage version 1.1.0.

Migration steps:

**1.** Unlink the react-native-webengage SDK from your project
```
cd YourProject/

react-native unlink react-native-webengage
```

**2.** Update the SDK.
```
npm install react-native-webengage@latest --save
```

**3.**  Link the SDK (in-case autolinking did not work).
```
react-native link react-native-webengage
```

**4.** Verify the ios/Podfile. Make sure that pod for react-native-webengage is added as shown below.
```
target 'YourProject' do
    ...
    pod 'react-native-webengage', :path => '../node_modules/react-native-webengage'
    ...
end
```

**5.** Reinstall the pods.
```
cd ios

pod deintegrate

rm Podfile.lock

rm -rf YourProject.xcworkspace

pod install --repo-update
```

Now open YourProject.xcworkspace and run the app.

**Comment by ashwindmk** [comment]
For errors in the SDK such as:
```
fatal error: 'React/RCTBridgeModule.h' file not found
```

The reason is that React module was not found by the react-native-webengage SDK. Please make sure that all the required pods are specified in the Podfile in recommended order.

Use the following Podfile for reference: https://github.com/WebEngage/react-native-webengage/blob/master/ExampleApp/ios/Podfile

If still the error persists, make sure that you have the latest cocoapods, react-native-cli, node/npm and Xcode installed, then try upgrading and regenerating the xcodeproj file using the following command:
```
react-native upgrade 0.60.4 --legacy true
```

**Comment by guggume** [comment]
@ashwindmk thank you, updated to new package and it started working.
