### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method. 

### ISSUE THREAD

**Issue by imanshul** [WebEngage/react-native-webengage#60]
When we add react-native-webengage and creates a object for the same in App.js this warning came.

It sends around 14 warnings for the same

Versions:
react-naitve-webengage: "1.4.1"
react-native: "0.73.1",

**Comment by imanshul** [comment]
@BhaveshWebEngage  can you please also look into this and provide a fix for the same. It's idle from very long.

**Comment by BhaveshWebEngage** [comment]
Thank you for your patience. We'll prioritize investigating and addressing this issue promptly. 
Rest assured, we'll follow up with you once we have a resolution/investigation.
Thank you for bringing this to our attention.

**Comment by akshay-engage** [comment]
Hi @imanshul 

This issue is fixed in our latest version. Please update to the latest version. Closing this issue now.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
