### ISSUE TITLE
Multiple commands produce 

### ISSUE THREAD

**Issue by omkarKiranaClub** [WebEngage/react-native-webengage#66]
Multiple commands produce '/Users/omkarsalapurkar/Library/Developer/Xcode/DerivedData/kiranaclub-epdzjeavhjpvqzflqfrjwowiwsvj/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/WebEngage/WebEngage.framework'

I am facing this issue whenever i try to create these targets as per the docs for Rich push notifications
==>
Step 1: In Xcode, navigate to File > New > Target and select Notification Service Extension.

Step 2: Click Next, fill out the Product Name as NotificationService, and click Finish.

Step 1: In Xcode, navigate to File > New > Target and select Notification Content Extension.

Step 2: Click Next, fill out the Product Name as NotificationViewController, and click Finish

When i add these the below error comes => Multiple commands produce
Please help!
@akshay-engage

**Comment by akshay-engage** [comment]
The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "WebEngage" framework.
Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.
To address this concern effectively, we strongly recommend following these steps: 
1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes. 
2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict. 
3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate. 
We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future. 
Should you require any further assistance, have questions, or need additional guidance, please don't hesitate to reach out to us.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
